import { useState } from 'react';
import Head from 'next/head';
import { NextPage } from 'next';
import { ConnectButton } from '@rainbow-me/rainbowkit';

const Create: NextPage = () => {
  const [inputValue, setInputValue] = useState('');

  const handleInputChange = (event: React.ChangeEvent<HTMLTextAreaElement>) => {
    setInputValue(event.target.value);
  };

  const handleSubmit = (event: React.FormEvent) => {
    event.preventDefault();
    // Handle form submission here
  };

  return (
    <main className='h-screen w-screen py-16 flex flex-col items-center justify-center'>
      <Head>
        <title>Story chain</title>
        <meta
          content='Generated by @rainbow-me/create-rainbowkit'
          name='Help write your communities story'
        />
        <link href='/favicon.ico' rel='icon' />
      </Head>

      <div className='flex-1 w-1/2 flex flex-col items-center justify-start py-16'>
        <h1 className='text-4xl md:text-6xl lg:text-7xl text-center mb-8'>
          Write part of your community&apos;s story
        </h1>
        <form onSubmit={handleSubmit} className='flex flex-col items-center'>
          <textarea
            value={inputValue}
            onChange={handleInputChange}
            maxLength={50}
            placeholder='Insert here fren'
            className='px-4 py-2 border border-gray-300 rounded-lg resize-none mb-4'
            rows={4}
          />
          <button
            type='submit'
            className='bg-blue-500 text-white px-4 py-2 rounded-lg'
          >
            Submit
          </button>
        </form>
      </div>

      <footer className='flex items-center justify-center py-8 border-t border-gray-300'>
        <a
          href='https://trooplabs.lol/'
          rel='noopener noreferrer'
          target='_blank'
        >
          Made with ❤️ by your frens at Troop labs
        </a>
      </footer>
    </main>
  );
};

export default Create;
