import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';

const Login: NextPage = () => {
  return (
    <main className='h-screen w-screen py-16 flex flex-col items-center justify-center'>
      <Head>
        <title>Story chain</title>
        <meta
          content='Generated by @rainbow-me/create-rainbowkit'
          name='Help write your communities story'
        />
        <link href='/favicon.ico' rel='icon' />
      </Head>

      <main className='flex-1 flex flex-col items-center justify-center py-16'>
        <h1 className='text-4xl md:text-6xl lg:text-7xl text-center mb-8'>
          Bonjour! <br /> Welcome to story chain
        </h1>
        <ConnectButton />
      </main>

      <footer className='flex items-center justify-center py-8 border-t border-gray-300'>
        <a
          href='https://trooplabs.lol/'
          rel='noopener noreferrer'
          target='_blank'
        >
          Made with ❤️ by your frens at Troop labs
        </a>
      </footer>
    </main>
  );
};

export default Login;
